# Custom Language File for Launcher Customizer

[ejs.app]
title = "연말 서버"

[ejs.landing]
mediaGitHubURL = "https://github.com/mchlauncher/shirayukiHina"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/shirayukiHina"
supportLink = "https://github.com/mchlauncher/shirayukiHina/issues"

[ejs.welcome]
welcomeHeader = "연말 서버"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."